# Netlifyの認証機能と連携するための設定
backend:
  name: git-gateway
  branch: main # GitHubリポジトリのメインブランチ名（mainまたはmasterが一般的）

# 画像などのメディアファイルを保存する場所
media_folder: "static/images/uploads" # 画像はここに保存される
public_folder: "/images/uploads" # 保存された画像がサイトで表示されるきのパス

# 編集するコンテンツ（コレクション）の設定
collections:
  - name: "post" # コレクションの名前（管理画面で表示される）
    label: "投稿" # 管理画面での表示名
    folder: "content/posts" # 編集対象のファイルが保存されているフォルダ
    create: true # 新規作成を許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # ファイル名のルール
    fields: # 編集する項目
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "下書き", name: "draft", widget: "boolean", default: true}
      - {label: "本文", name: "body", widget: "markdown"}