backend:
  name: git-gateway
  repo: surtr417/mysite # ご自身のGitHubユーザー名/リポジトリ名に書き換えてください
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "ブログ記事"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "下書き", name: "draft", widget: "boolean", default: true }
      - { label: "カテゴリー", name: "categories", widget: "list", required: false }
      - { label: "タグ", name: "tags", widget: "list", required: false }
      - { label: "本文", name: "body", widget: "markdown" }
