# backend: あなたのサイトのリポジトリ情報を設定します
backend:
  name: git-gateway
  repo: surtr417/mysite # ★★★ あなたのGitHubリポジトリ名に書き換えてください (例: "gleeful-caramel/my-airspace-site")

# media_folder: CMSでアップロードした画像を保存する場所
# public_folder: サイト上で画像が表示される際のパス
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# collections: サイトの各コンテンツセクションの編集設定
collections:
- name: "pages"                     # 内部的な識別名
  label: "固定ページ"                 # 管理画面での表示名
  files:                            # folder: の代わりに files: を使う
    - name: "homepage"              # ファイルの識別名
      label: "ホームページ"         # 管理画面での表示名
      file: "content/_index.md"     # 編集対象のファイルパス
      fields:                       # そのファイルが持つフィールドの定義
        - { label: "メイン見出し", name: "heading", widget: "string" }
        - { label: "紹介文", name: "intro", widget: "markdown" }
    - name: "about"
      label: "会社概要"
      file: "content/about.md"
      fields:
        - { label: "ページタイトル", name: "title", widget: "string" }
        - { label: "本文", name: "body", widget: "markdown" }
